Auth and general refactoring
liwoo/flutter-firebase-bloc-starter pull request #20
Opened 2021-12-13 22:56 UTC by sevenreup

- moved auth to flutter fire ui..

2021-12-13 23:10 UTC, liwoo requested changes

2021-12-13 23:10 UTC, liwoo commented on lib/src/app.dart
> +      home: Notifier(
what'd this for?

2021-12-13 23:10 UTC, liwoo commented on lib/src/screens/settings.dart
> +class SettingItem extends StatelessWidget {
this should be in the setting folder in a file of its own

2021-12-14 21:58 UTC, sevenreup commented on lib/src/app.dart
> +      home: Notifier(
😅😅 It was on the first PR on auth, I don't remember.

2021-12-15 20:14 UTC, closed without merging